### ISSUE TITLE
Conflict with User Agent Overrider

### ISSUE THREAD

**Issue by Josh54** [diegocr/PrefMon#3]
This has a conflict with the extension found here: https://addons.mozilla.org/en-US/firefox/addon/user-agent-overrider/

Preferences Monitor by default changes settings that the User Agent Overrider changes and so they fight it out, so to speak, and the end result is an empty string (which disables some sites). One way to get it working is to make PrefMon not reverse any changes automatically, but this seems like an unsatisfying solution. Also, why would the string end up being empty?

**Comment by diegocr** [comment]
Hi Josh54,

All you have to do is whitelisting that add-on:

![14092817467](https://f.cloud.github.com/assets/734313/2296572/91ae2704-a0a0-11e3-9a56-02d7822010b1.gif)

I.e: Copy&paste this to the end of that option as shown in the screenshoot:

  `;User Agent Overrider:^general\.useragent\.override`

As to why the string ends up being empty, it's because that pref doesn't exists by default. However, indeed PrefMon should be resetting the pref rather than leaving it just empty, i think Firefox would take care of this but it shouldn't if you have noticed side effects from this.
